const data = [
  {
    name: "Palm Harbor",
    location: "Noida, India",
    price: 2999,
    date: "2023-03-12",
    type: "House",
    image: "https://img.staticmb.com/mbcontent/images/uploads/2022/12/Most-Beautiful-House-in-the-World.jpg",
    details: {
      beds: 2,
      bathrooms: 1,
      l: "7",
      b: "5",
    },
    popular: false,
    liked: false,
  },
  {
    name: "Cross Villa",
    location: "Jaipur, Rajasthan, India",
    price: 5999,
    date: "2023-06-11",
    type: "Villa",
    image: "https://www.gemsbougainvillas.in/wp-content/uploads/2021/08/villa-verde-4bhk-kolkata-mob.jpg",
    details: {
      beds: 7,
      bathrooms: 3,
      l: "10",
      b: "15",
    },
    popular: true,
    liked: false,
  },
  {
    name: "Beverly Springfield",
    location: "Banglore, Karnataka, India",
    price: 3999,
    date: "2023-05-10",
    type: "Bungalow",
    image: "https://www.thespruce.com/thmb/zFg7mPetp_7ZVqcScgJHbc7PSTg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-523075374-8d27b929fdfc4702aab5c73f821a65de.jpg",
    details: {
      beds: 4,
      bathrooms: 2,
      l: "9",
      b: "10",
    },
    popular: false,
    liked: false,
  },
  {
    name: "Faulkner Ave",
    location: "Chennai, Tamil Nadu, India",
    price: 3999,
    date: "2023-05-10",
    type: "Mansion",
    image: "https://static1.mansionglobal.com/production/media/listing_images/5f50beaa11a132caea5ff7eb2905f05a/xlarge_6722_Calle_Ponte_Bella__1_.jpg",
    details: {
      beds: 4,
      bathrooms: 2,
      l: "9",
      b: "10",
    },
    popular: false,
    liked: false,
  },
  {
    name: "Century",
    location: "Kolkata, West Bengal, India",
    price: 1999,
    date: "2023-02-10",
    type: "House",
    image: "https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/home-improvement/wp-content/uploads/2022/07/download-23.jpg",
    details: {
      beds: 3,
      bathrooms: 1,
      l: "5",
      b: "7",
    },
    popular: false,
    liked: false,
  },
  {
    name: "Pachmarhi",
    location: "Pachmarhi , Madhya Pradesh, India",
    price: 3999,
    date: "2023-07-20",
    type: "Bungalow",
    image: "https://i.pinimg.com/736x/dc/ca/c0/dccac025c8eb9230602645efea380db6.jpg",
    details: {
      beds: 5,
      bathrooms: 3,
      l: "12",
      b: "17",
    },
    popular: false,
    liked: false,
  },
  {
    name: "Washington",
    location: "New Delhi , New Delhi, India",
    price: 5999,
    date: "2022-11-29",
    type: "House",
    image: "https://res.cloudinary.com/brickandbatten/images/f_auto,q_auto/v1675439478/wordpress_assets/SmallHouseExteriors-Twitter-card-B-LOGO/SmallHouseExteriors-Twitter-card-B-LOGO.jpg?_i=AA",
    details: {
      beds: 4,
      bathrooms: 2,
      l: "10",
      b: "10",
    },
    popular: false,
    liked: false,
  },
  {
    name: "Shadows",
    location: "Mumbai, Maharashtra, India",
    price: 7999,
    date: "2024-08-05",
    type: "Mansion",
    image: "https://images.mansionglobal.com/im-53085137?width=1299&height=866",
    details: {
      beds: 9,
      bathrooms: 5,
      l: "20",
      b: "20",
    },
    popular: true,
    liked: false,
  },
];

export default data;